-- MySQL Script generated by MySQL Workbench
-- Sat Feb 17 22:01:18 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`EMPLOYEE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EMPLOYEE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`EMPLOYEE` (
  `EmployeeID` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(30) NULL,
  `LastName` VARCHAR(30) NULL,
  `Email` VARCHAR(100) NULL,
  `PhoneNumber` VARCHAR(10) NULL,
  `HireDate` DATE NULL,
  `DateofBirth` DATE NULL,
  `PayRate` INT NULL,
  PRIMARY KEY (`EmployeeID`),
  UNIQUE INDEX `User ID_UNIQUE` (`EmployeeID` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `mydb`.`STORES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`STORES` ;

CREATE TABLE IF NOT EXISTS `mydb`.`STORES` (
  `StoreName` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`StoreName`));


-- -----------------------------------------------------
-- Table `mydb`.`ROLES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ROLES` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ROLES` (
  `RoleName` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`RoleName`));


-- -----------------------------------------------------
-- Table `mydb`.`SCHEDULE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`SCHEDULE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`SCHEDULE` (
  `ScheduleID` INT NOT NULL AUTO_INCREMENT,
  `StartDate` DATE NULL,
  `EndDate` DATE NULL,
  `ScheduleName` VARCHAR(45) NULL,
  PRIMARY KEY (`ScheduleID`),
  UNIQUE INDEX `ScheduleID_UNIQUE` (`ScheduleID` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `mydb`.`SHIFT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`SHIFT` ;

CREATE TABLE IF NOT EXISTS `mydb`.`SHIFT` (
  `ShiftID` INT NOT NULL AUTO_INCREMENT,
  `Date` DATE NULL,
  `StartTime` TIME NULL,
  `EndTIme` TIME NULL,
  `EMPLOYEE_EmployeeID` INT NULL,
  `STORES_StoreName` VARCHAR(30) NOT NULL,
  `SCHEDULE_ScheduleID` INT NOT NULL,
  `ROLES_RoleName` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`ShiftID`),
  UNIQUE INDEX `ShiftID_UNIQUE` (`ShiftID` ASC) VISIBLE,
  INDEX `fk_SHIFT_EMPLOYEE1_idx` (`EMPLOYEE_EmployeeID` ASC) VISIBLE,
  INDEX `fk_SHIFT_STORES1_idx` (`STORES_StoreName` ASC) VISIBLE,
  INDEX `fk_SHIFT_SCHEDULE1_idx` (`SCHEDULE_ScheduleID` ASC) VISIBLE,
  INDEX `fk_SHIFT_ROLES1_idx` (`ROLES_RoleName` ASC) VISIBLE,
  CONSTRAINT `fk_SHIFT_EMPLOYEE1`
    FOREIGN KEY (`EMPLOYEE_EmployeeID`)
    REFERENCES `mydb`.`EMPLOYEE` (`EmployeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SHIFT_STORES1`
    FOREIGN KEY (`STORES_StoreName`)
    REFERENCES `mydb`.`STORES` (`StoreName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SHIFT_SCHEDULE1`
    FOREIGN KEY (`SCHEDULE_ScheduleID`)
    REFERENCES `mydb`.`SCHEDULE` (`ScheduleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SHIFT_ROLES1`
    FOREIGN KEY (`ROLES_RoleName`)
    REFERENCES `mydb`.`ROLES` (`RoleName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`AVAILABILITY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`AVAILABILITY` ;

CREATE TABLE IF NOT EXISTS `mydb`.`AVAILABILITY` (
  `AvailabilityID` INT NOT NULL AUTO_INCREMENT,
  `StartTime` TIME NULL,
  `EndTime` TIME NULL,
  `DayOfWeek` INT NULL,
  `EMPLOYEE_EmployeeID` INT NOT NULL,
  `SCHEDULE_ScheduleID` INT NULL,
  PRIMARY KEY (`AvailabilityID`),
  INDEX `fk_AVAILABILITY_EMPLOYEE1_idx` (`EMPLOYEE_EmployeeID` ASC) VISIBLE,
  INDEX `fk_AVAILABILITY_SCHEDULE1_idx` (`SCHEDULE_ScheduleID` ASC) VISIBLE,
  CONSTRAINT `fk_AVAILABILITY_EMPLOYEE1`
    FOREIGN KEY (`EMPLOYEE_EmployeeID`)
    REFERENCES `mydb`.`EMPLOYEE` (`EmployeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AVAILABILITY_SCHEDULE1`
    FOREIGN KEY (`SCHEDULE_ScheduleID`)
    REFERENCES `mydb`.`SCHEDULE` (`ScheduleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`DESIREDSHIFTHOURS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DESIREDSHIFTHOURS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DESIREDSHIFTHOURS` (
  `DesiredShiftHoursID` INT NOT NULL AUTO_INCREMENT,
  `DesiredShifts` INT NULL,
  `MaxShifts` INT NULL,
  `DesiredHours` INT NULL,
  `MaxHours` INT NULL,
  `EMPLOYEE_EmployeeID` INT NOT NULL,
  `SCHEDULE_ScheduleID` INT NULL,
  PRIMARY KEY (`DesiredShiftHoursID`),
  INDEX `fk_DESIREDSHIFTHOURS_EMPLOYEE1_idx` (`EMPLOYEE_EmployeeID` ASC) VISIBLE,
  INDEX `fk_DESIREDSHIFTHOURS_SCHEDULE1_idx` (`SCHEDULE_ScheduleID` ASC) VISIBLE,
  CONSTRAINT `fk_DESIREDSHIFTHOURS_EMPLOYEE1`
    FOREIGN KEY (`EMPLOYEE_EmployeeID`)
    REFERENCES `mydb`.`EMPLOYEE` (`EmployeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DESIREDSHIFTHOURS_SCHEDULE1`
    FOREIGN KEY (`SCHEDULE_ScheduleID`)
    REFERENCES `mydb`.`SCHEDULE` (`ScheduleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`EMPLOYEE_has_ROLES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EMPLOYEE_has_ROLES` ;

CREATE TABLE IF NOT EXISTS `mydb`.`EMPLOYEE_has_ROLES` (
  `EMPLOYEE_EmployeeID` INT NOT NULL,
  `ROLES_RoleName` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`EMPLOYEE_EmployeeID`, `ROLES_RoleName`),
  INDEX `fk_EMPLOYEE_has_ROLES_ROLES1_idx` (`ROLES_RoleName` ASC) VISIBLE,
  INDEX `fk_EMPLOYEE_has_ROLES_EMPLOYEE1_idx` (`EMPLOYEE_EmployeeID` ASC) VISIBLE,
  CONSTRAINT `fk_EMPLOYEE_has_ROLES_EMPLOYEE1`
    FOREIGN KEY (`EMPLOYEE_EmployeeID`)
    REFERENCES `mydb`.`EMPLOYEE` (`EmployeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EMPLOYEE_has_ROLES_ROLES1`
    FOREIGN KEY (`ROLES_RoleName`)
    REFERENCES `mydb`.`ROLES` (`RoleName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`EMPLOYEE_has_STORES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EMPLOYEE_has_STORES` ;

CREATE TABLE IF NOT EXISTS `mydb`.`EMPLOYEE_has_STORES` (
  `EMPLOYEE_EmployeeID` INT NOT NULL,
  `STORES_StoreName` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`EMPLOYEE_EmployeeID`, `STORES_StoreName`),
  INDEX `fk_EMPLOYEE_has_STORES_STORES1_idx` (`STORES_StoreName` ASC) VISIBLE,
  INDEX `fk_EMPLOYEE_has_STORES_EMPLOYEE1_idx` (`EMPLOYEE_EmployeeID` ASC) VISIBLE,
  CONSTRAINT `fk_EMPLOYEE_has_STORES_EMPLOYEE1`
    FOREIGN KEY (`EMPLOYEE_EmployeeID`)
    REFERENCES `mydb`.`EMPLOYEE` (`EmployeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EMPLOYEE_has_STORES_STORES1`
    FOREIGN KEY (`STORES_StoreName`)
    REFERENCES `mydb`.`STORES` (`StoreName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
